// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace HBJYDev.Netbox
{
    public static class GetTenantGroup
    {
        public static Task<GetTenantGroupResult> InvokeAsync(GetTenantGroupArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetTenantGroupResult>("netbox:index/getTenantGroup:getTenantGroup", args ?? new GetTenantGroupArgs(), options.WithDefaults());

        public static Output<GetTenantGroupResult> Invoke(GetTenantGroupInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetTenantGroupResult>("netbox:index/getTenantGroup:getTenantGroup", args ?? new GetTenantGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTenantGroupArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetTenantGroupArgs()
        {
        }
        public static new GetTenantGroupArgs Empty => new GetTenantGroupArgs();
    }

    public sealed class GetTenantGroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetTenantGroupInvokeArgs()
        {
        }
        public static new GetTenantGroupInvokeArgs Empty => new GetTenantGroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetTenantGroupResult
    {
        public readonly string Description;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly int ParentId;
        public readonly string Slug;

        [OutputConstructor]
        private GetTenantGroupResult(
            string description,

            string id,

            string name,

            int parentId,

            string slug)
        {
            Description = description;
            Id = id;
            Name = name;
            ParentId = parentId;
            Slug = slug;
        }
    }
}
