// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace HBJYDev.Netbox
{
    public static class GetVrf
    {
        /// <summary>
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Netbox = Pulumi.Netbox;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var custAProd = Netbox.GetVrf.Invoke(new()
        ///     {
        ///         Name = "cust-a-prod",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetVrfResult> InvokeAsync(GetVrfArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetVrfResult>("netbox:index/getVrf:getVrf", args ?? new GetVrfArgs(), options.WithDefaults());

        /// <summary>
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Netbox = Pulumi.Netbox;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var custAProd = Netbox.GetVrf.Invoke(new()
        ///     {
        ///         Name = "cust-a-prod",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetVrfResult> Invoke(GetVrfInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetVrfResult>("netbox:index/getVrf:getVrf", args ?? new GetVrfInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetVrfArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("tenantId")]
        public int? TenantId { get; set; }

        public GetVrfArgs()
        {
        }
        public static new GetVrfArgs Empty => new GetVrfArgs();
    }

    public sealed class GetVrfInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("tenantId")]
        public Input<int>? TenantId { get; set; }

        public GetVrfInvokeArgs()
        {
        }
        public static new GetVrfInvokeArgs Empty => new GetVrfInvokeArgs();
    }


    [OutputType]
    public sealed class GetVrfResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly int? TenantId;

        [OutputConstructor]
        private GetVrfResult(
            string id,

            string name,

            int? tenantId)
        {
            Id = id;
            Name = name;
            TenantId = tenantId;
        }
    }
}
