// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace HBJYDev.Netbox
{
    /// <summary>
    /// The provider type for the netbox package. By default, resources use package-wide configuration
    /// settings, however an explicit `Provider` instance may be created and passed during resource
    /// construction to achieve fine-grained programmatic control over provider settings. See the
    /// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
    /// </summary>
    [NetboxResourceType("pulumi:providers:netbox")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// Netbox API authentication token
        /// </summary>
        [Output("apiToken")]
        public Output<string?> ApiToken { get; private set; } = null!;

        /// <summary>
        /// Location of Netbox server including scheme and optional port
        /// </summary>
        [Output("serverUrl")]
        public Output<string?> ServerUrl { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs? args = null, CustomResourceOptions? options = null)
            : base("netbox", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Flag to set whether to allow https with invalid certificates
        /// </summary>
        [Input("allowInsecureHttps", json: true)]
        public Input<bool>? AllowInsecureHttps { get; set; }

        /// <summary>
        /// Netbox API authentication token
        /// </summary>
        [Input("apiToken")]
        public Input<string>? ApiToken { get; set; }

        [Input("headers", json: true)]
        private InputMap<object>? _headers;

        /// <summary>
        /// Set these header on all requests to Netbox
        /// </summary>
        public InputMap<object> Headers
        {
            get => _headers ?? (_headers = new InputMap<object>());
            set => _headers = value;
        }

        /// <summary>
        /// Location of Netbox server including scheme and optional port
        /// </summary>
        [Input("serverUrl")]
        public Input<string>? ServerUrl { get; set; }

        /// <summary>
        /// If true, do not try to determine the running Netbox version at provider startup. Disables warnings about possibly
        /// unsupported Netbox version. Also useful for local testing on terraform plans.
        /// </summary>
        [Input("skipVersionCheck", json: true)]
        public Input<bool>? SkipVersionCheck { get; set; }

        public ProviderArgs()
        {
            ApiToken = Utilities.GetEnv("NETBOX_API_TOKEN");
            ServerUrl = Utilities.GetEnv("NETBOX_SERVER_URL");
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
