// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netbox

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/hbjydev/pulumi-netbox/sdk/go/netbox"
//	"github.com/pulumi/pulumi-netbox/sdk/go/netbox"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := netbox.LookupDeviceRole(ctx, &GetDeviceRoleArgs{
//				Name: "core-sw",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupDeviceRole(ctx *pulumi.Context, args *LookupDeviceRoleArgs, opts ...pulumi.InvokeOption) (*LookupDeviceRoleResult, error) {
	var rv LookupDeviceRoleResult
	err := ctx.Invoke("netbox:index/getDeviceRole:getDeviceRole", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDeviceRole.
type LookupDeviceRoleArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getDeviceRole.
type LookupDeviceRoleResult struct {
	ColorHex string `pulumi:"colorHex"`
	// The provider-assigned unique ID for this managed resource.
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
	Slug string `pulumi:"slug"`
}

func LookupDeviceRoleOutput(ctx *pulumi.Context, args LookupDeviceRoleOutputArgs, opts ...pulumi.InvokeOption) LookupDeviceRoleResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupDeviceRoleResult, error) {
			args := v.(LookupDeviceRoleArgs)
			r, err := LookupDeviceRole(ctx, &args, opts...)
			var s LookupDeviceRoleResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupDeviceRoleResultOutput)
}

// A collection of arguments for invoking getDeviceRole.
type LookupDeviceRoleOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupDeviceRoleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDeviceRoleArgs)(nil)).Elem()
}

// A collection of values returned by getDeviceRole.
type LookupDeviceRoleResultOutput struct{ *pulumi.OutputState }

func (LookupDeviceRoleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDeviceRoleResult)(nil)).Elem()
}

func (o LookupDeviceRoleResultOutput) ToLookupDeviceRoleResultOutput() LookupDeviceRoleResultOutput {
	return o
}

func (o LookupDeviceRoleResultOutput) ToLookupDeviceRoleResultOutputWithContext(ctx context.Context) LookupDeviceRoleResultOutput {
	return o
}

func (o LookupDeviceRoleResultOutput) ColorHex() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDeviceRoleResult) string { return v.ColorHex }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupDeviceRoleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDeviceRoleResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupDeviceRoleResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDeviceRoleResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupDeviceRoleResultOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDeviceRoleResult) string { return v.Slug }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDeviceRoleResultOutput{})
}
