// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netbox

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/hbjydev/pulumi-netbox/sdk/go/netbox"
//	"github.com/pulumi/pulumi-netbox/sdk/go/netbox"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := netbox.LookupPlatform(ctx, &GetPlatformArgs{
//				Name: "PANOS",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupPlatform(ctx *pulumi.Context, args *LookupPlatformArgs, opts ...pulumi.InvokeOption) (*LookupPlatformResult, error) {
	var rv LookupPlatformResult
	err := ctx.Invoke("netbox:index/getPlatform:getPlatform", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPlatform.
type LookupPlatformArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getPlatform.
type LookupPlatformResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
	Slug string `pulumi:"slug"`
}

func LookupPlatformOutput(ctx *pulumi.Context, args LookupPlatformOutputArgs, opts ...pulumi.InvokeOption) LookupPlatformResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupPlatformResult, error) {
			args := v.(LookupPlatformArgs)
			r, err := LookupPlatform(ctx, &args, opts...)
			var s LookupPlatformResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupPlatformResultOutput)
}

// A collection of arguments for invoking getPlatform.
type LookupPlatformOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupPlatformOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPlatformArgs)(nil)).Elem()
}

// A collection of values returned by getPlatform.
type LookupPlatformResultOutput struct{ *pulumi.OutputState }

func (LookupPlatformResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPlatformResult)(nil)).Elem()
}

func (o LookupPlatformResultOutput) ToLookupPlatformResultOutput() LookupPlatformResultOutput {
	return o
}

func (o LookupPlatformResultOutput) ToLookupPlatformResultOutputWithContext(ctx context.Context) LookupPlatformResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupPlatformResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPlatformResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupPlatformResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPlatformResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupPlatformResultOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPlatformResult) string { return v.Slug }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupPlatformResultOutput{})
}
