// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netbox

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/hbjydev/pulumi-netbox/sdk/go/netbox"
//	"github.com/pulumi/pulumi-netbox/sdk/go/netbox"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := netbox.LookupTenant(ctx, &GetTenantArgs{
//				Name: "Customer A",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupTenant(ctx *pulumi.Context, args *LookupTenantArgs, opts ...pulumi.InvokeOption) (*LookupTenantResult, error) {
	var rv LookupTenantResult
	err := ctx.Invoke("netbox:index/getTenant:getTenant", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTenant.
type LookupTenantArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getTenant.
type LookupTenantResult struct {
	GroupId int `pulumi:"groupId"`
	// The provider-assigned unique ID for this managed resource.
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
	Slug string `pulumi:"slug"`
}

func LookupTenantOutput(ctx *pulumi.Context, args LookupTenantOutputArgs, opts ...pulumi.InvokeOption) LookupTenantResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupTenantResult, error) {
			args := v.(LookupTenantArgs)
			r, err := LookupTenant(ctx, &args, opts...)
			var s LookupTenantResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupTenantResultOutput)
}

// A collection of arguments for invoking getTenant.
type LookupTenantOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupTenantOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTenantArgs)(nil)).Elem()
}

// A collection of values returned by getTenant.
type LookupTenantResultOutput struct{ *pulumi.OutputState }

func (LookupTenantResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTenantResult)(nil)).Elem()
}

func (o LookupTenantResultOutput) ToLookupTenantResultOutput() LookupTenantResultOutput {
	return o
}

func (o LookupTenantResultOutput) ToLookupTenantResultOutputWithContext(ctx context.Context) LookupTenantResultOutput {
	return o
}

func (o LookupTenantResultOutput) GroupId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupTenantResult) int { return v.GroupId }).(pulumi.IntOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupTenantResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupTenantResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupTenantResultOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.Slug }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupTenantResultOutput{})
}
