// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netbox

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the netbox package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// Netbox API authentication token
	ApiToken pulumi.StringPtrOutput `pulumi:"apiToken"`
	// Location of Netbox server including scheme and optional port
	ServerUrl pulumi.StringPtrOutput `pulumi:"serverUrl"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if isZero(args.ApiToken) {
		args.ApiToken = pulumi.StringPtr(getEnvOrDefault("", nil, "NETBOX_API_TOKEN").(string))
	}
	if isZero(args.ServerUrl) {
		args.ServerUrl = pulumi.StringPtr(getEnvOrDefault("", nil, "NETBOX_SERVER_URL").(string))
	}
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:netbox", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// Flag to set whether to allow https with invalid certificates
	AllowInsecureHttps *bool `pulumi:"allowInsecureHttps"`
	// Netbox API authentication token
	ApiToken *string `pulumi:"apiToken"`
	// Set these header on all requests to Netbox
	Headers map[string]interface{} `pulumi:"headers"`
	// Location of Netbox server including scheme and optional port
	ServerUrl *string `pulumi:"serverUrl"`
	// If true, do not try to determine the running Netbox version at provider startup. Disables warnings about possibly
	// unsupported Netbox version. Also useful for local testing on terraform plans.
	SkipVersionCheck *bool `pulumi:"skipVersionCheck"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// Flag to set whether to allow https with invalid certificates
	AllowInsecureHttps pulumi.BoolPtrInput
	// Netbox API authentication token
	ApiToken pulumi.StringPtrInput
	// Set these header on all requests to Netbox
	Headers pulumi.MapInput
	// Location of Netbox server including scheme and optional port
	ServerUrl pulumi.StringPtrInput
	// If true, do not try to determine the running Netbox version at provider startup. Disables warnings about possibly
	// unsupported Netbox version. Also useful for local testing on terraform plans.
	SkipVersionCheck pulumi.BoolPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// Netbox API authentication token
func (o ProviderOutput) ApiToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiToken }).(pulumi.StringPtrOutput)
}

// Location of Netbox server including scheme and optional port
func (o ProviderOutput) ServerUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ServerUrl }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
