// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// Flag to set whether to allow https with invalid certificates
func GetAllowInsecureHttps(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "netbox:allowInsecureHttps")
}

// Netbox API authentication token
func GetApiToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "netbox:apiToken")
	if err == nil {
		return v
	}
	return getEnvOrDefault("", nil, "NETBOX_API_TOKEN").(string)
}

// Set these header on all requests to Netbox
func GetHeaders(ctx *pulumi.Context) string {
	return config.Get(ctx, "netbox:headers")
}

// Location of Netbox server including scheme and optional port
func GetServerUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "netbox:serverUrl")
	if err == nil {
		return v
	}
	return getEnvOrDefault("", nil, "NETBOX_SERVER_URL").(string)
}

// If true, do not try to determine the running Netbox version at provider startup. Disables warnings about possibly
// unsupported Netbox version. Also useful for local testing on terraform plans.
func GetSkipVersionCheck(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "netbox:skipVersionCheck")
}
