// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace HBJYDev.Netbox.Inputs
{

    public sealed class GetInterfacesFilterArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("value", required: true)]
        public string Value { get; set; } = null!;

        public GetInterfacesFilterArgs()
        {
        }
        public static new GetInterfacesFilterArgs Empty => new GetInterfacesFilterArgs();
    }
}
