// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * From the [official documentation](https://docs.netbox.dev/en/stable/core-functionality/circuits/#circuit-types):
 *
 * > Circuits are classified by functional type. These types are completely customizable, and are typically used to convey the type of service being delivered over a circuit.
 */
export class CircuitType extends pulumi.CustomResource {
    /**
     * Get an existing CircuitType resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CircuitTypeState, opts?: pulumi.CustomResourceOptions): CircuitType {
        return new CircuitType(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbox:index/circuitType:CircuitType';

    /**
     * Returns true if the given object is an instance of CircuitType.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CircuitType {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CircuitType.__pulumiType;
    }

    public readonly name!: pulumi.Output<string>;
    public readonly slug!: pulumi.Output<string>;

    /**
     * Create a CircuitType resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CircuitTypeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CircuitTypeArgs | CircuitTypeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CircuitTypeState | undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["slug"] = state ? state.slug : undefined;
        } else {
            const args = argsOrState as CircuitTypeArgs | undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["slug"] = args ? args.slug : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CircuitType.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CircuitType resources.
 */
export interface CircuitTypeState {
    name?: pulumi.Input<string>;
    slug?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CircuitType resource.
 */
export interface CircuitTypeArgs {
    name?: pulumi.Input<string>;
    slug?: pulumi.Input<string>;
}
