// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getIpAddresses(args?: GetIpAddressesArgs, opts?: pulumi.InvokeOptions): Promise<GetIpAddressesResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("netbox:index/getIpAddresses:getIpAddresses", {
        "filters": args.filters,
    }, opts);
}

/**
 * A collection of arguments for invoking getIpAddresses.
 */
export interface GetIpAddressesArgs {
    filters?: inputs.GetIpAddressesFilter[];
}

/**
 * A collection of values returned by getIpAddresses.
 */
export interface GetIpAddressesResult {
    readonly filters?: outputs.GetIpAddressesFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ipAddresses: outputs.GetIpAddressesIpAddress[];
}

export function getIpAddressesOutput(args?: GetIpAddressesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetIpAddressesResult> {
    return pulumi.output(args).apply(a => getIpAddresses(a, opts))
}

/**
 * A collection of arguments for invoking getIpAddresses.
 */
export interface GetIpAddressesOutputArgs {
    filters?: pulumi.Input<pulumi.Input<inputs.GetIpAddressesFilterArgs>[]>;
}
